version: 2.1

orbs:
  perl:
    description: Helpers for testing Perl project on Linux (in Docker) with CircleCI

    commands:
      pre-build:
        description: Prepare the build for caching
        parameters:
          perl-version:
            description: The version of the runtime Perl being used
            type: string
        steps:
          - run:
              name: Pre build
              command: |
                ~/circleci-perl-helpers-tools/bin/with-perl build-perl pre-build.pl \
                    --runtime-perl << parameters.perl-version >>
      restore-authordeps-cache:
        description: Restore cached authordeps needed to build the distro
        steps:
          - restore_cache:
              keys:
                - v6-authordeps-linux-{{ checksum "/root/cache/authordeps" }}-{{ checksum "/root/cache/build-perl-version" }}
      install-authordeps:
        description: Install deps needed to build the distro
        steps:
          - run:
              name: Install authordeps
              command: ~/circleci-perl-helpers-tools/bin/with-perl build-perl install-authordeps.pl
      save-authordeps-cache:
        description: Save authordeps needed to build the distro
        steps:
          - save_cache:
              key: v6-authordeps-linux-{{ checksum "/root/cache/authordeps" }}-{{ checksum "/root/cache/build-perl-version" }}
              paths: /root/perl-local/build-perl
      build-dist:
        description: Build the distro and put it in a separate directory for test running
        steps:
          - run:
              name: Build distro
              command: ~/circleci-perl-helpers-tools/bin/with-perl build-perl build-dist.pl
      build-cpanfile:
        description: Build a cpanfile for the distro's runtime deps to facilitate caching
        steps:
          - run:
              name: Build cpanfile for distro
              command: ~/circleci-perl-helpers-tools/bin/with-perl build-perl build-cpanfile.pl
      restore-prereqs-cache:
        description: Restore cached runtime deps needed to test the distro
        parameters:
          disable-runtime-cache:
            description: If this is true then caching of runtime deps will be skipped. This should be true for all blead builds.
            type: boolean
        steps:
          - unless:
              condition: << parameters.disable-runtime-cache >>
              steps:
                - restore_cache:
                    keys:
                      - v6-prereqs-linux-{{ checksum "/root/cache/prereqs-cpanfile" }}-{{ checksum "/root/cache/runtime-perl-version" }}
      install-prereqs:
        description: Install deps needed to build the distro
        steps:
          - run:
              name: Install deps
              command: ~/circleci-perl-helpers-tools/bin/with-perl build-perl install-prereqs.pl
      save-prereqs-cache:
        description: Save runtime deps needed to test the distro
        parameters:
          disable-runtime-cache:
            description: If this is true then caching of runtime deps will be skipped. This should be true for all blead builds.
            type: boolean
        steps:
          - unless:
              condition: << parameters.disable-runtime-cache >>
              steps:
                - save_cache:
                    key: v6-prereqs-linux-{{ checksum "/root/cache/prereqs-cpanfile" }}-{{ checksum "/root/cache/runtime-perl-version" }}
                    paths: /root/perl-local/runtime-perl
      prep-distro-for-tests:
        description: Run final make/Build commands needed to prep distro for tests
        steps:
          - run:
              name: Run make or Build
              command: ~/circleci-perl-helpers-tools/bin/with-perl build-perl prep-for-tests.pl
      run-test-with-prove:
        description: Run tests with prove
        steps:
          - run:
              name: Run tests
              command: ~/circleci-perl-helpers-tools/bin/with-perl build-perl run-tests.pl

    jobs:
      linux-build-and-test:
        description: Builds the Perl distro and runs its tests using prove
        parameters:
          perl-version:
            description: Which version of Perl to use for this job
            type: string
          run-xt-tests:
            description: |
              If this is true tests in the xt directory will be true, and the
              AUTHOR_TESTING and RELEASE_TESTING env vars will be set to true
              values when running tests.
            type: boolean
            default: false
          disable-runtime-cache:
            description: |
              If this is true then caching of runtime deps will be
              skipped. This should be true for all blead builds since blead's
              ABI may change between runs, breaking previously compiled XS
              code.
            type: boolean
            default: false
          debug:
            description: Enable verbose output from each step.
            type: boolean
            default: false
        docker:
          - image: houseabsolute/circleci-perl-helpers-ubuntu:<< parameters.perl-version >>
            environment:
              CCI_PERL_HELPERS_TEST_XT: <<# parameters.run-xt-tests >>1<</ parameters.run-xt-tests >>
              CCI_PERL_HELPERS_DEBUG: <<# parameters.debug >>1<</ parameters.debug >>
        steps:
          - checkout
          - pre-build:
              perl-version: << parameters.perl-version >>
          - restore-authordeps-cache
          - install-authordeps
          - save-authordeps-cache
          - build-dist
          - build-cpanfile
          - restore-prereqs-cache:
              disable-runtime-cache: << parameters.disable-runtime-cache >>
          - install-prereqs
          - save-prereqs-cache:
              disable-runtime-cache: << parameters.disable-runtime-cache >>
          - prep-distro-for-tests
          - run-test-with-prove

workflows:
  version: 2
  test-all-perls:
    jobs:
      - perl/linux-build-and-test:
          name: linux-5.28.2
          perl-version: "5.28.2"
      - perl/linux-build-and-test:
          name: linux-blead
          perl-version: "blead"
          disable-runtime-cache: true
